name: Flutter CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y curl unzip xz-utils zip libglu1-mesa

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7.3' # Specify the Flutter version you need

    - name: Flutter Pub Get
      run: flutter pub get

    - name: Flutter Analyze
      run: flutter analyze

    - name: Flutter Build APK
      run: flutter build apk --release

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    - name: Create credentials.json
      run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > scripts/credentials.json

    - name: Upload to Google Drive
      run: |
        python scripts/upload_to_drive.py build/app/outputs/flutter-apk/app-release.apk ${{ secrets.GDRIVE_FOLDER_ID }}
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $GITHUB_WORKSPACE/scripts/credentials.json
