name: Test Secrets

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Print GOOGLE_APPLICATION_CREDENTIALS_JSON
      run: echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}"

    - name: Print GDRIVE_FOLDER_ID
      run: echo "${{ secrets.GDRIVE_FOLDER_ID }}"
